[package]
name = "tokimk"
version = "0.202002.1"
authors = ["fuyutarow <fuyutarow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.104"
serde_derive = "1.0.104"
toml = "0.5.6"
structopt = "0.3.9"
dirs = "2.0.2"
