[package]
name = "rc-make"
version = "0.1.0"
authors = ["fuyutarow"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
dirs = "3.0.2"
serde = "1.0.125"
serde_derive = "1.0.125"
toml = "0.5.8"

[lib]
name = 'cli'
path = 'src/lib/mod.rs'
