[package]
authors = ["fuyutarow <fuyutarow@gmail.com>"]
edition = "2018"
name = "rcmk"
version = "0.202103.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0.2"
serde = "1.0.104"
serde_derive = "1.0.104"
structopt = "0.3.9"
toml = "0.5.6"
