[package]
name = "env-make"
version = "0.202105.2"
authors = ["fuyutarow"]
edition = "2018"

[lib]
name = 'cli'
path = 'src/lib/mod.rs'

[dependencies]
anyhow = "1.0.40"
dirs = "3.0.2"
indexmap = { version = "1.6.2", features = ["serde"] }
serde = "1.0.125"
serde_derive = "1.0.125"
toml = "0.5.8"
