[tasks.hot]
run_task = {name = ["build", "move-bin", "local-install"]}

[tasks.move-bin]
script = [
  '''
cp ./target/release/rcmk ./bin/
''',
]

[tasks.build]
args = ["build", "--release"]
command = "cargo"

[tasks.local-install]
script = [
  '''
cp ./target/release/rcmk ~/.local/bin/
''',
]
